/*
 * This source file was generated by the Gradle 'init' task
 */
package hellojava;

import java.util.Set;
import java.util.TreeSet;
import java.util.HashSet;
import java.util.List;
import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("=== For Loop와 컬렉션 수정 실험 ===\n");

        // 1. ArrayList - 순회 중 추가
        System.out.println("1. ArrayList - 순회 중 추가:");
        List<Integer> list = new ArrayList<>();
        list.add(1);
        list.add(2);
        list.add(3);

        try {
            for (Integer num : list) {
                System.out.println("현재: " + num);
                if (num == 2) {
                    list.add(99);  // 💥 ConcurrentModificationException!
                }
            }
        } catch (Exception e) {
            System.out.println("❌ 예외 발생: " + e.getClass().getSimpleName());
        }

        // 2. TreeSet - 순회 중 추가
        System.out.println("\n2. TreeSet - 순회 중 추가:");
        TreeSet<Integer> treeSet = new TreeSet<>();
        treeSet.add(1);
        treeSet.add(2);
        treeSet.add(3);

        try {
            for (Integer num : treeSet) {
                System.out.println("현재: " + num);
                if (num == 2) {
                    treeSet.add(99);  // 💥 ConcurrentModificationException!
                }
            }
        } catch (Exception e) {
            System.out.println("❌ 예외 발생: " + e.getClass().getSimpleName());
        }

        // 3. 안전한 방법 1: 인덱스 기반 for loop (List만 가능)
        System.out.println("\n3. 안전한 방법 - 인덱스 기반 for:");
        List<Integer> safeList = new ArrayList<>();
        safeList.add(1);
        safeList.add(2);
        safeList.add(3);

        for (int i = 0; i < safeList.size(); i++) {
            System.out.println("현재: " + safeList.get(i));
            if (safeList.get(i) == 2) {
                safeList.add(99);  // ✅ 작동! (하지만 무한루프 주의)
                break;  // 무한루프 방지
            }
        }
        System.out.println("결과: " + safeList);

        // 4. 안전한 방법 2: 임시 리스트 사용
        System.out.println("\n4. 안전한 방법 - 임시 리스트:");
        TreeSet<Integer> originalSet = new TreeSet<>();
        originalSet.add(1);
        originalSet.add(2);
        originalSet.add(3);

        List<Integer> toAdd = new ArrayList<>();
        for (Integer num : originalSet) {
            System.out.println("현재: " + num);
            if (num == 2) {
                toAdd.add(99);
            }
        }
        originalSet.addAll(toAdd);
        System.out.println("결과: " + originalSet);

        // 5. 안전한 방법 3: Iterator 사용
        System.out.println("\n5. 안전한 방법 - Iterator:");
        List<Integer> iterList = new ArrayList<>();
        iterList.add(1);
        iterList.add(2);
        iterList.add(3);

        java.util.Iterator<Integer> iterator = iterList.iterator();
        while (iterator.hasNext()) {
            Integer num = iterator.next();
            System.out.println("현재: " + num);
            if (num == 2) {
                iterator.remove();  // ✅ Iterator를 통한 제거는 안전
            }
        }
        System.out.println("결과: " + iterList);

        // 6. CopyOnWriteArrayList - 순회 중 수정 가능
        System.out.println("\n6. CopyOnWriteArrayList - 순회 중 수정 가능:");
        java.util.concurrent.CopyOnWriteArrayList<Integer> cowList =
            new java.util.concurrent.CopyOnWriteArrayList<>();
        cowList.add(1);
        cowList.add(2);
        cowList.add(3);

        for (Integer num : cowList) {
            System.out.println("현재: " + num);
            if (num == 2) {
                cowList.add(99);  // ✅ 작동! (하지만 이번 순회에는 안 보임)
            }
        }
        System.out.println("결과: " + cowList);

        System.out.println("\n=== 실험 완료 ===");
    }
}
